### PR TITLE
fix

### LINKED ISSUE #2: Fix my menu

### PR DESCRIPTION
**Pull request by piotrkardasz**
I think this Fixes #2

### CODE REVIEW

File: calculator/calculator/Program.cs [hunk 1]
```diff
@@ -16,13 +16,12 @@ static void Main(string[] args)
                 Console.WriteLine("2.Odejmij");
                 Console.WriteLine("3.Mnozenie.");
                 Console.WriteLine("4.Dzielenie");
-                Console.WriteLine("5.Exit");
+                Console.WriteLine("5. Naprawione xD");
```
Comment (piegus32) [inline calculator/calculator/Program.cs]: No ja mysle...

File: calculator/calculator/Program.cs [hunk 2]
```diff
@@ -16,13 +16,12 @@ static void Main(string[] args)
                 Console.WriteLine("2.Odejmij");
                 Console.WriteLine("3.Mnozenie.");
                 Console.WriteLine("4.Dzielenie");
```
Comment (piegus32) [inline calculator/calculator/Program.cs]: tralalal

**Comment by piegus32** [comment]
Niech CI bedzie
